### ISSUE TITLE
Unable to find MySQL bin path

### ISSUE THREAD

**Issue by ghost** [jbox-web/job-database-manager-mysql#9]
Hello,

I'm trying to use your plugin which correspond exactly to what I would like to do .

But I can't figure out the correct value for the field : "Jenkins MySQL bin path".

The default value is not working and I can't find a way to visualize my intern jenkins file in order to find the correct path.

Do I need to install something else ? an other plugin (I installed ruby-runtime) ?
 You don't mention it in the readme as if it shouldn't be an issue  so I guess that I missed a point.

**Comment by n-rodriguez** [comment]
Hi! 

> But I can't figure out the correct value for the field : "Jenkins MySQL bin path".

Usually it's `/usr/bin/mysql`. You'll need MySQL or MariaDB to be installed on your Jenkins node.

**Comment by ghost** [comment]
Hi, thanks for your answer but I can't find a way to get mysql installed on my node, It should be done with a plugin or ,manually ?

**Comment by n-rodriguez** [comment]
> It should be done with a plugin or ,manually ?

Usually it's done manually with your package manager (`apt` on Debian/Ubuntu or `yum` on RedHat/Fedora)
